project:
  type: website
  output-dir: docs

website:
  title: "Five-tab-website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - Other.qmd
      - Another.qmd
      - Almost.qmd
      - Last.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

